import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  CreditCardIcon,
  User,
  User2Icon,
  UserX2Icon,
  X,
  Activity,
  Gauge,
  FileSpreadsheet,
  PlayCircle,
  RadioIcon,
  Globe,
  LayoutGrid,
  Album,
  Mic2,
  ListMusic,
  LibraryBigIcon,
  LineChart,
  Podcast,
  Text,
  Video,
} from "lucide-react";
import { PiChalkboardTeacherBold, PiHandCoins } from "react-icons/pi";
import { AiOutlineTransaction } from "react-icons/ai";
import { TbZip } from "react-icons/tb";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  reports: FileSpreadsheet,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  video: Video,
  activity: Activity,
  playCircle: PlayCircle,
  radio: RadioIcon,
  globe: Globe,
  layoutGrid: LayoutGrid,
  album: Album,
  mic2: Mic2,
  musicList: ListMusic,
  library: LibraryBigIcon,
  stastics: LineChart,
  podcast: Podcast,
  coinHand: CreditCardIcon,
  image: Image,
  txt: Text,
  zip: TbZip,
  pay: PiHandCoins,
  transaction: AiOutlineTransaction,
  coach: PiChalkboardTeacherBold,
  gauge: Gauge,
  check: Check,
};
